In [11]:
import pandas as pd
import sqlite3
from statsmodels.tsa.statespace.sarimax import SARIMAX

In [12]:
# first things first, extract tables from database
conn = sqlite3.connect("../backend/database/reports.db")

In [13]:
master_df = pd.read_sql_query("SELECT * FROM community_reports", conn)
master_df.head()

,id,community_name,region_id,report_date,reporter_type,local_season,rainfall_level,road_access,seasonal_indicators_text,num_dogs_seen,num_puppies_seen,skin_issue_count,parasite_issue_count,recent_dog_deaths,distance_to_clinic,dog_roaming_level,requested_help,notes
0,1,Maningrida,1,2026-04-10 22:15:43,community_member,Kudjewk,high,difficult,"first rains, flooding, flowering trees",24,7,4,5,1,120,high,1,"Several dogs scratching, more puppies than usu..."

In [14]:
master_df.dtypes

id                          int64
community_name                str
region_id                   int64
report_date                   str
reporter_type                 str
local_season                  str
rainfall_level                str
road_access                   str
seasonal_indicators_text      str
num_dogs_seen               int64
num_puppies_seen            int64
skin_issue_count            int64
parasite_issue_count        int64
recent_dog_deaths           int64
distance_to_clinic          int64
dog_roaming_level             str
requested_help              int64
notes                         str
dtype: object

In [15]:
# assuming we extract all 4 databases (MASTER, avg_df, known_val_feature_df, seasonal_constraints), preprocess master DB, THENNN (also preprocessing may be done backend, or maybe not)
# im doing preprocessing of master DB first
# so first removing un-needed columns:
print(master_df.columns.tolist())
master_df = master_df.drop(columns=["id", "community_name", "reporter_type", "seasonal_indicators_text", "notes"])
master_df.dtypes

# now we gotta convert everything to numeric
# these are report_date, local_season, rainfall_level, road_access, dog_roaming_level
# for local_season, gotta make maps tho:
season_map = {
    "Kudjewk": 1,
    "Bangkerreng": 2,
    "Yekke": 3,
    "Wurrkeng": 4,
    "Kurrung": 5,
    "Kunumeleng": 6
}

rainfall_map = {
    "high": 3,
    "medium": 2,
    "low": 1
}

road_access_map = {
    "difficult": 1,
    "moderate": 2,
    "easy": 3
}

dog_roaming_map = {
    "high": 3,
    "medium": 2,
    "low": 1
}

master_df["local_season"] = master_df["local_season"].map(season_map)
master_df["rainfall_level"] = master_df["rainfall_level"].map(rainfall_map)
master_df["road_access"] = master_df["road_access"].map(road_access_map)
master_df["dog_roaming_level"] = master_df["dog_roaming_level"].map(dog_roaming_map)

master_df.head()

['id', 'community_name', 'region_id', 'report_date', 'reporter_type', 'local_season', 'rainfall_level', 'road_access', 'seasonal_indicators_text', 'num_dogs_seen', 'num_puppies_seen', 'skin_issue_count', 'parasite_issue_count', 'recent_dog_deaths', 'distance_to_clinic', 'dog_roaming_level', 'requested_help', 'notes']

,region_id,report_date,local_season,rainfall_level,road_access,num_dogs_seen,num_puppies_seen,skin_issue_count,parasite_issue_count,recent_dog_deaths,distance_to_clinic,dog_roaming_level,requested_help
0,1,2026-04-10 22:15:43,1,3,1,24,7,4,5,1,120,3,1

In [20]:
# now we gotta convert report_date into proper date format and make it id
master_df["report_date"] = pd.to_datetime(master_df["report_date"])
master_df = master_df.set_index("report_date")
master_df.head()
master_df.dtypes

region_id               int64
local_season            int64
rainfall_level          int64
road_access             int64
num_dogs_seen           int64
num_puppies_seen        int64
skin_issue_count        int64
parasite_issue_count    int64
recent_dog_deaths       int64
distance_to_clinic      int64
dog_roaming_level       int64
requested_help          int64
dtype: object

In [24]:
# LESGOOO Now there is one last preprocessing step. We need to make this into a month ting...
# So like make a month by month table for each of these tings.
monthly_df = master_df.drop(columns=["region_id"])
monthly_df = monthly_df.resample("MS").agg({
    "num_dogs_seen": "mean",
    "num_puppies_seen": "mean",
    "skin_issue_count": "mean",
    "recent_dog_deaths": "mean",
    "parasite_issue_count": "mean",
    "distance_to_clinic": "mean",
    "local_season": lambda x: x.mode().iloc[0],
    "rainfall_level": lambda x: x.mode().iloc[0],
    "road_access": lambda x: x.mode().iloc[0],
    "dog_roaming_level": lambda x: x.mode().iloc[0],
    "requested_help": lambda x: x.mode().iloc[0]
}).reset_index()

monthly_df.head()

,report_date,num_dogs_seen,num_puppies_seen,skin_issue_count,recent_dog_deaths,parasite_issue_count,distance_to_clinic,local_season,rainfall_level,road_access,dog_roaming_level,requested_help
0,2026-04-01,24.0,7.0,4.0,1.0,5.0,120.0,1,3,1,3,1

In [ ]:
# Nowwwww, we gotta put each of those into SARIMAX
# first, we put ONE of them into SARIMAX. Lets do it slowllyyy..........
# lets first do master_df_p1
p1_y = master_df_p1["p1_outbreak_value"]
p1_x = master_df_p1[[col1, col2, col3, ...]] # everything except p1 outbreak value (ALSO, EXCEPT THE DATE. SAME FOR P2,P3)
p1_model = SARIMAX(
    p1_y,
    exog=p1_x,
    order=(1,0,1), # these params may be changed
    seasonal_order=(1,1,1,12) # params may change
)
p1_result = p1_model.fit()

# now master_df_p2
p2_y = master_df_p2["p2_outbreak_value"]
p2_x = master_df_p2[[col1, col2, col3, ...]] # everything except p2 outbreak value
p2_model = SARIMAX(
    p2_y,
    exog=p2_x,
    order=(1,0,1), # these params may be changed
    seasonal_order=(1,1,1,12) # params may change
)
p2_result = p2_model.fit()

# master_df_p3
p3_y = master_df_p3["p3_outbreak_value"]
p3_x = master_df_p3[[col1, col2, col3, ...]] # everything except p3 outbreak value
p3_model = SARIMAX(
    p3_y,
    exog=p3_x,
    order=(1,0,1), # these params may be changed
    seasonal_order=(1,1,1,12) # params may change
)
p3_result = p3_model.fit()

In [30]:
# now we should make the apply dataset (same for all p1, p2, p3)

# make sure date column in og DF is in datetime format
date_col = "Date"   # change this to your actual date column name

master_without_outputs = master_df_p1.drop(columns=["p1_outbreak_value"])

# get the latest date in the original df
last_date = master_without_outputs[date_col].max()

# first day of next 3 months
future_dates = pd.date_range(
    start=(last_date + pd.offsets.MonthBegin(1)).normalize(),
    periods=3,
    freq="MS"
)

# create empty df with same columns, 3 rows
future_df = pd.DataFrame(columns=master_without_outputs.columns, index=range(3)) # this is our apply df

# fill date column
future_df[date_col] = future_dates

NameError: name 'master_df_p1' is not defined

In [17]:
# now we should fill up the apply dataset with all em values...
# get month number for each future row
future_df["MonthNum"] = future_df[date_col].dt.month

# fill chosen features from averages table
for i, row in future_df.iterrows():
    month_num = row["MonthNum"]

    # get the row from avg_df for that month
    avg_row = avg_df[avg_df["Month"] == month_num] # here avg_df is extracted from our master storage 

    if not avg_row.empty:
        for col in avg_features:
            if col in future_df.columns and col in avg_df.columns:
                future_df.at[i, col] = avg_row.iloc[0][col]

# fill features from known_value_features table
for i, row in future_df.iterrows():
    month_num = row["Month"]
    known_row = known_val_feature_df[known_val_feature_df["Month"] == month_num] # here known_val_feature_df is also extracted from master storage

    if not known_row.empty:
        for col in known_val_feature_df.columns:
            if col != "Month" and col in future_df.columns:
                future_df.at[i, col] = known_row.iloc[0][col]

# remove helper column
future_df = future_df.drop(columns="MonthNum")

In [19]:
# Now we gotta run these through each of the models for p1, p2, p3 lollllll
# ok so firstly, the format of future_df must be THE SAME as our training df (preprocessed master DB), mneaning that
# format and dtypes of each column shld be same, etc.... also make sure theres no NaN values or any of that

In [ ]:
future_X = future_df[[col1, col2, col3, ...]] # all columns except DATE (theres no output column here anyway)
forecast_p1 = p1_result.forecast(steps=len(future_X), exog=future_X)
forecast_p2 = p2_result.forecast(steps=len(future_X), exog=future_X)
forecast_p3 = p3_result.forecast(steps=len(future_X), exog=future_X)